# import = [
#   '~/.config/alacritty/themes/themes/ubuntu.toml'
# ]

[font]
size = 16.0

[font.bold]
family = 'SF Mono'
style = 'Regular'
# style = 'Semibold'

[font.normal]
family = 'SF Mono'
style = 'Regular'

[font.italic]
family = 'SF Mono'
style = 'Regular'

[font.bold_italic]
family = 'SF Mono'
style = 'Regular'

[window]
decorations = 'buttonless'
