# import = [
#   '~/.config/alacritty/themes/themes/ubuntu.toml'
# ]

[font]
size = 16.0

[font.bold]
style = 'Regular'

[font.normal]
style = 'Regular'

[font.italic]
style = 'Regular'

[font.bold_italic]
style = 'Regular'

[window]
decorations = 'buttonless'
